apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-blue
      release: v1
  template:
    metadata:
      labels:
        app: frontend-blue
        release: v1
    spec:
      containers:
      - image: lxqhim/smart-bank-frontend:blue
        imagePullPolicy: IfNotPresent
        name: frontend-blue
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: 
          limits:
            cpu: 20m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 50Mi  

